### ISSUE TITLE
AttributeError: module 'lief' has no attribute 'not_found'

### ISSUE THREAD

**Issue by ImSo3K** [dhondta/bintropy#4]
Referring to the following except statement:
https://github.com/packing-box/bintropy/blob/ea89b1484131a8db0561b065f229ee11c33a33ae/src/bintropy/__init__.py#L89

It seems like that in LIEF's latest update ([0.13.0](https://github.com/lief-project/LIEF/releases/tag/0.13.0)) they no longer use exceptions, this can be seen in their [official docs](https://lief-project.github.io/doc/latest/api/python/index.html#exceptions) too.

As a temporary fix, I just deleted these 2 attributes which results in:
`except AttributeError: `

**Comment by ImSo3K** [comment]
Another thing that I've noticed, in the following line:
https://github.com/packing-box/bintropy/blob/ea89b1484131a8db0561b065f229ee11c33a33ae/src/bintropy/__init__.py#L78
will result in  `btype = '_lief'` since `type(binary)` returns `<class 'lief._lief.PE.Binary>` so taking the next element in the split `[2]` will result in `PE`

I haven't tested this with ELF or Mach0 file types

**Comment by dhondta** [comment]
Hi @ImSo3K 
Thank you for bringing this to my attention ! Fixed in 1.4.2.

**Comment by ImSo3K** [comment]
> Hi @ImSo3K Thank you for bringing this to my attention ! Fixed in 1.4.2.

Sure no problem, I did actually find another instance of the same issue with `btype` when I plotted the result.
You can see it here:
https://github.com/packing-box/bintropy/blob/c866725045bf4fc5bb551e0659bb7e7b4fcbbf7f/src/bintropy/__init__.py#L228
In my case, it just said `Entropy per section of _lief file` instead of PE, the same fix worked for me there too
